### ISSUE TITLE
Process for resizing the cluster

### ISSUE THREAD

**Issue by ShurikAg** [digitalocean/Kubernetes-Starter-Kit-Developers#113] opened 2022-01-24 20:56 UTC
We bootstrapped the cluster following [these docs](https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/tree/main/15-automate-with-terraform-flux#step-2---bootstrapping-doks-and-flux-cd) and created the fully-functioning deployment of the app.  Eventually, it appeared that we need more nodes.

If I understand correctly, all I need to do is to update `main.tf` with more nodes and follow the same process of applying the changes. However, when I was trying to run: `terraform plan -out priz_prod_cluster.out` I got an error:

```
╷
│ Error: Error retrieving Kubernetes cluster: GET https://api.digitalocean.com/v2/kubernetes/clusters/f9883560-f07a-4e54-9520-97f3210cb47b: 401 Unable to authenticate you
│
│   with module.doks_flux_cd.digitalocean_kubernetes_cluster.primary,
│   on .terraform/modules/doks_flux_cd/create-doks-with-terraform-flux/main.tf line 39, in resource "digitalocean_kubernetes_cluster" "primary":
│   39: resource "digitalocean_kubernetes_cluster" "primary" {
```

Is that expected? Am I doing anything wrong?

**Comment by ShurikAg** [comment] 2022-01-24 21:38
Looks like I had a wrong do_api_token. Fixed that, and not I am getting the following error:

```
│ Error: Get "http://localhost/api/v1/namespaces/flux-system": dial tcp [::1]:80: connect: connection refused
│
│   with module.doks_flux_cd.kubernetes_namespace.flux_system,
│   on .terraform/modules/doks_flux_cd/create-doks-with-terraform-flux/main.tf line 52, in resource "kubernetes_namespace" "flux_system":
│   52: resource "kubernetes_namespace" "flux_system" {
```

**Comment by v-ctiutiu** [comment] 2022-01-25 08:26
Hi @ShurikAg 

Thanks for submitting the issue.

Let me try to reproduce this scenario and get back to you. Thanks.

**Comment by v-ctiutiu** [comment] 2022-01-28 11:48
Hi @ShurikAg 

Sorry for the late response. I managed to reproduce your issue, and I'm currently working on a fix. Seems to be a bug in our Terraform module. Will let you know when it's ready.

Thanks.

**Comment by v-ctiutiu** [comment] 2022-01-28 19:05
A fix is already in progress, via [container-blueprints #25](https://github.com/digitalocean/container-blueprints/issues/25).

**Comment by v-ctiutiu** [comment] 2022-02-01 10:22
@ShurikAg 

Managed to fix the issue in the upstream repository (where the custom TF module is hosted). All you have to do in your existing TF workspace is this:

1. Fetch the updated TF module from the upstream repository:

    ```shell
    terraform get -update
    ```

2. Modify the `doks_cluster_pool_node_count` variable to suit your needs in the `main.tf` file from your workspace.
3. Create the plan:

     ```shell
     terraform plan -out priz_prod_cluster.out
     ```

At the end Terrraform should show you that it is going to modify the node count from the pool. Something similar to (in my tests, I changed to **node count** from **1** to **2**):

```text
# module.doks_flux_cd.digitalocean_kubernetes_cluster.primary will be updated in-place
  ~ resource "digitalocean_kubernetes_cluster" "primary" {
        id             = "70cbf156-9415-43ba-a7b7-4e8cdfc7dc66"
        name           = "fluxcd-demo"
        tags           = []
        # (14 unchanged attributes hidden)


      ~ node_pool {
            id                = "7131414a-05de-47b5-9396-7853ea2f3312"
            name              = "fluxcd-demo-pool"
          ~ node_count        = 1 -> 2
            tags              = []
            # (7 unchanged attributes hidden)
        }
        # (1 unchanged block hidden)
    }
```

Please test and let me know how it goes.

Thanks.

**Comment by bikram20** [comment] 2022-02-08 04:26
@v-ctiutiu We should mark this as resolved since the PR is already merged.

**Closed** 2022-02-08 15:22 UTC
Labels: bug
